export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const UPDATE_USER = "UPDATE_USER";

export const QUERY_API = "QUERY_API";
export const RESET_FETCHING_STATE = "RESET_FETCHING_STATE";
export const ADD_NEW_HOLDING = "ADD_NEW_HOLDING";